name: LumiBot CI/CD
on: [push]
jobs:
  LintAndTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: pip
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install -r requirements_dev.txt
          python setup.py install
      - name: Run Linter
        run: |
          # Remove -e flag to fail the run if issues are found
          ruff check . -e
      - name: Run Unit Tests
        run: |
          coverage run
          coverage report
          coverage html
